import { StyleSheet } from "react-native";

export const homeScannerStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  scanInputContainer: {
    // paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#e0e0e0",
    // backgroundColor: "yellow",
  },
  scanInputBox: {
    backgroundColor: "#f5f5f5",
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "center",
    // gap: 15,
    // height: 84,
    marginHorizontal: 16,
    paddingHorizontal: 16,
    borderRadius: 20,
    borderWidth: 0.2,
    borderColor: "#000",
  },
  scanRow: {
    marginVertical: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 15,
  },
  scanCameraBox: {
    backgroundColor: "white",
    paddingVertical: 6,
    paddingHorizontal: 26,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e0e0e0",
    // borderColor: "#000",
  },
  scanBox: {
    flex: 1,
    height: 42,
    marginLeft: 12,
    marginRight: 4,
    transform: "translateY(-10px)",
  },
  scanText: {
    fontSize: 12,
    color: "#000",
    textAlign: "center",
    marginBottom: 4,
  },
  codeText: {
    color: "black",
    fontSize: 16,
    height: 48,
    backgroundColor: "white",
  },
  tableWrapper: {
    flex: 1,
    marginBottom: 80, // Space for the bottom button
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  tableContainer: {
    flex: 1,
  },
  groupContainer: {
    marginBottom: 24,
    borderWidth: 1,
    borderColor: "#e0e0e0",
    borderRadius: 8,
    overflow: "hidden",
  },
  groupHeader: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#e0e0e0",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  groupHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  groupHeaderText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333",
  },
  groupHeaderSubText: {
    fontSize: 14,
    color: "#666",
    marginLeft: 8,
  },
  buttonView: {
    padding: 16,
    width: "100%",
    position: "absolute",
    bottom: 0,
    backgroundColor: "#fff",
    borderTopWidth: 1,
    borderTopColor: "#e0e0e0",
    flexDirection: "row",
    justifyContent: "center",
    gap: 16,
  },
  cancelButton: {
    backgroundColor: "#f5f5f5",
    borderRadius: 8,
    width: 100,
    borderWidth: 1,
    borderColor: "#e0e0e0",
  },
  cancelButtonText: {
    color: "#333",
    fontWeight: "600",
  },
  newAllocationButton: {
    width: "100%",
    backgroundColor: "#fff",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#1570EF",
    height: 48,
    justifyContent: "center",
  },
  newAllocationButtonText: {
    color: "#1570EF",
    fontSize: 14,
    fontWeight: "600",
  },
  allocateButton: {
    flex: 1,
    backgroundColor: "#1570EF",
    borderRadius: 8,
    height: 48,
    justifyContent: "center",
    color: "white",
  },
  snackbar: {
    margin: 16,
    borderRadius: 8,
  },
  snackbarText: {
    fontSize: 14,
    fontWeight: "500",
    textAlign: "center",
    color: "#fff",
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#f5f5f5",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderColor: "#ddd",
  },

  tableRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderColor: "#eee",
  },
  headerCell: {
    fontWeight: "bold",
    textAlign: "center",
    paddingHorizontal: 4,
  },

  cell: {
    textAlign: "center",
    paddingHorizontal: 4,
  },
  postAllocationHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 16,
    paddingHorizontal: 24,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#e0e0e0",
  },
  postAllocationSection: {
    flexDirection: "column",
  },
  postAllocationLabel: {
    fontSize: 14,
    fontWeight: "bold",
    color: "green",
  },
  postAllocationValue: {
    fontSize: 16,
    textAlign: "center",
    fontWeight: "600",
    color: "#333",
    marginTop: 4,
  },
});
